=== garfieldyao/dbexport/mapping/MappingSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" attributeFormDefault="unqualified"
	xmlns="http://www.garfield.com/MappingSchema" targetNamespace="http://www.garfield.com/MappingSchema">

	<xsd:element name="mappings">
		<xsd:complexType>
			<xsd:sequence>
				<!-- xsd:element name="tablename" type="xsd:string"></xsd:element -->
				<xsd:element name="mapping" type="MappingType"
					minOccurs="1" maxOccurs="65535"></xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="MappingType">
		<xsd:sequence>
			<xsd:element name="attributes">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="prefix" type="xsd:string"></xsd:element>
						<xsd:element name="miniAttributes" type="xsd:integer"
							default="0" minOccurs="0" maxOccurs="1"></xsd:element>
						<xsd:element name="attribute" type="AttributeType"
							minOccurs="1" maxOccurs="65535">
						</xsd:element>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="AttributeType">
		<xsd:sequence>
			<xsd:element name="cliname" type="xsd:string" minOccurs="1"
				maxOccurs="1"></xsd:element>
			<xsd:element name="dbTable" type="xsd:string" minOccurs="1"
				maxOccurs="1"></xsd:element>
			<xsd:element name="dbAttribute" type="xsd:string"
				minOccurs="1" maxOccurs="1"></xsd:element>
			<xsd:element name="index" type="xsd:string" minOccurs="1"
				maxOccurs="1"></xsd:element>
			<xsd:element name="parser" type="xsd:string" default="auto"
				minOccurs="0" maxOccurs="1"></xsd:element>
			<xsd:element name="novalue" type="boolean" default="false"
				minOccurs="0" maxOccurs="1"></xsd:element>
			<xsd:element name="default" type="xsd:string" minOccurs="0"
				maxOccurs="1"></xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:simpleType name="boolean">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="true"></xsd:enumeration>
			<xsd:enumeration value="false"></xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>

</xsd:schema>

=== garfieldyao/dbexport/mapping/DataMapping2_vlan.xml
<?xml version="1.0" encoding="UTF-8"?>
<mappings xmlns="http://www.garfield.com/MappingSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.garfield.com/MappingSchema MappingSchema.xsd ">
	<!-- configure vlan id -->
	<mapping>
		<attributes>
			<prefix>configure vlan</prefix>
			<miniAttributes>1</miniAttributes>
			<attribute>
				<cliname>id</cliname>
				<dbTable>vlanStaTbl</dbTable>
				<dbAttribute>vlanId</dbAttribute>
				<index>vlanId(class:com.mars.dbexport.service.parse.VlanIdParser)</index>
				<parser>class:com.mars.dbexport.service.parse.VlanIdParser</parser>
			</attribute>
			<attribute>
				<cliname>mode</cliname>
				<dbTable>vlanStaTbl</dbTable>
				<dbAttribute>vSysMod</dbAttribute>
				<index>vlanId(class:com.mars.dbexport.service.parse.VlanIdParser)</index>
				<parser>enum:(0x10000,cross-connect)(0x20000,residential-bridge)(0x30000,qos-aware)(0x40000,layer2-terminated)(0x70000,mirror)</parser>
			</attribute>
			<attribute>
				<cliname>name</cliname>
				<dbTable>vlanStaTbl</dbTable>
				<dbAttribute>vStaNm</dbAttribute>
				<index>vlanId(class:com.mars.dbexport.service.parse.VlanIdParser)</index>
			</attribute>
			<attribute>
				<cliname>sntp-proxy</cliname>
				<dbTable>vlanStaTbl</dbTable>
				<dbAttribute>sntpPxy</dbAttribute>
				<index>vlanId(class:com.mars.dbexport.service.parse.VlanIdParser)</index>
				<parser>bool:0</parser>
				<novalue>true</novalue>
			</attribute>
			<attribute>
				<cliname>priority</cliname>
				<dbTable>vlanStaTbl</dbTable>
				<dbAttribute>vStaPri</dbAttribute>
				<index>vlanId(class:com.mars.dbexport.service.parse.VlanIdParser)</index>
				<parser>reverse</parser>
				<default>0</default>
			</attribute>
			<attribute>
				<cliname>vmac-not-in-opt61</cliname>
				<dbTable>vlanStaTbl</dbTable>
				<dbAttribute>macOp61</dbAttribute>
				<index>vlanId(class:com.mars.dbexport.service.parse.VlanIdParser)</index>
				<parser>bool:0</parser>
				<novalue>true</novalue>
			</attribute>
			<attribute>
				<cliname>new-broadcast</cliname>
				<dbTable>vlanStaTbl</dbTable>
				<dbAttribute>vlanBcC</dbAttribute>
				<index>vlanId(class:com.mars.dbexport.service.parse.VlanIdParser)</index>
				<parser>enum:(0x3,enable)(0x4,disable)(0x5,inherit)</parser>
				<default>inherit</default>
			</attribute>
			<attribute>
				<cliname>protocol-filter</cliname>
				<dbTable>vlanStaTbl</dbTable>
				<dbAttribute>vGrouId</dbAttribute>
				<index>vlanId(class:com.mars.dbexport.service.parse.VlanIdParser)</index>
				<parser>enum:(0x30,pass-all)(0x31,pass-pppoe)(0x32,pass-ipoe)(0x33,pass-pppoe-ipoe)(0x34,pass-ipv6oe)(0x35,pass-pppoe-ipv6oe)(0x36,pass-ipoe-ipv6oe)(0x37,pass-pppoe-ipoe-ipv6oe)</parser>
				<default>pass-all</default>
			</attribute>
			<attribute>
				<cliname>pppoe-relay-tag</cliname>
				<dbTable>vlanStaTbl</dbTable>
				<dbAttribute>AdReTag</dbAttribute>
				<index>vlanId(class:com.mars.dbexport.service.parse.VlanIdParser)</index>
				<parser>enum:(0x1,true)(0x2,false)(0x3,configurable)</parser>
				<default>false</default>
			</attribute>
			<attribute>
				<cliname>new-secure-fwd</cliname>
				<dbTable>vlanStaTbl</dbTable>
				<dbAttribute>vSecFwd</dbAttribute>
				<index>vlanId(class:com.mars.dbexport.service.parse.VlanIdParser)</index>
				<parser>enum:(0x3,enable)(0x4,disable)(0x5,inherit)</parser>
				<default>inherit</default>
			</attribute>
			<attribute>
				<cliname>aging-time</cliname>
				<dbTable>vlanStaTbl</dbTable>
				<dbAttribute>macAgTm</dbAttribute>
				<index>vlanId(class:com.mars.dbexport.service.parse.VlanIdParser)</index>
				<default>4294967295</default>
			</attribute>
			<attribute>
				<cliname>l2cp-transparent</cliname>
				<dbTable>vlanStaTbl</dbTable>
				<dbAttribute>l2cpTra</dbAttribute>
				<index>vlanId(class:com.mars.dbexport.service.parse.VlanIdParser)</index>
				<parser>bool:0</parser>
				<novalue>true</novalue>
			</attribute>
			<attribute>
				<cliname>in-qos-prof-name</cliname>
				<dbTable>vlanStaTbl</dbTable>
				<dbAttribute>InQosTc</dbAttribute>
				<index>vlanId(class:com.mars.dbexport.service.parse.VlanIdParser)</index>
				<parser>ref:(QosInProf:Index:Name)</parser>
				<default>Ingress_Default</default>
			</attribute>
		</attributes>
	</mapping>
</mappings>

=== garfieldyao/dbexport/mapping/DataMapping5_qos.xml
<?xml version="1.0" encoding="UTF-8"?>
<mappings xmlns="http://www.garfield.com/MappingSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.garfield.com/MappingSchema MappingSchema.xsd ">
	<!-- configure qos interface -->
	<!-- ONT level QoS -->
	<mapping>
		<attributes>
			<prefix>configure qos</prefix>
			<miniAttributes>2</miniAttributes>
			<attribute>
				<cliname>interface</cliname>
				<dbTable>QosOnt</dbTable>
				<dbAttribute>logId</dbAttribute>
				<index>logId(regx|ont:1/1/|(32,8,-2)(23,9,1)(16,7,1))</index>
				<parser>regx|ont:1/1/|(32,8,-2)(23,9,1)(16,7,1)</parser>
			</attribute>
			<attribute>
				<cliname>scheduler-node</cliname>
				<dbTable>QosOnt</dbTable>
				<dbAttribute>scnProf</dbAttribute>
				<index>logId(regx|ont:1/1/|(32,8,-2)(23,9,1)(16,7,1))</index>
				<parser>ref|name:|(QosScNode:Index:Name)</parser>
			</attribute>
			<attribute>
				<cliname>ds-queue-sharing</cliname>
				<dbTable>QosOnt</dbTable>
				<dbAttribute>dsQShar</dbAttribute>
				<index>logId(regx|ont:1/1/|(32,8,-2)(23,9,1)(16,7,1))</index>
				<parser>bool:0</parser>
				<novalue>true</novalue>
			</attribute>
			<attribute>
				<cliname>us-queue-sharing</cliname>
				<dbTable>QosOnt</dbTable>
				<dbAttribute>usQShar</dbAttribute>
				<index>logId(regx|ont:1/1/|(32,8,-2)(23,9,1)(16,7,1))</index>
				<parser>bool:0</parser>
				<novalue>true</novalue>
			</attribute>
			<attribute>
				<cliname>ds-num-rem-queue</cliname>
				<dbTable>QosOnt</dbTable>
				<dbAttribute>dsNumRQ</dbAttribute>
				<index>logId(regx|ont:1/1/|(32,8,-2)(23,9,1)(16,7,1))</index>
				<parser>auto:(0x0,not-applicable)</parser>
				<default>not-applicable</default>
			</attribute>
			<attribute>
				<cliname>us-num-queue</cliname>
				<dbTable>QosOnt</dbTable>
				<dbAttribute>usNumQ</dbAttribute>
				<index>logId(regx|ont:1/1/|(32,8,-2)(23,9,1)(16,7,1))</index>
				<default>8</default>
			</attribute>
			<attribute>
				<cliname>us-vlanport-queue</cliname>
				<dbTable>QosOnt</dbTable>
				<dbAttribute>vpQEn</dbAttribute>
				<index>logId(regx|ont:1/1/|(32,8,-2)(23,9,1)(16,7,1))</index>
				<parser>bool:0</parser>
				<novalue>true</novalue>
			</attribute>
		</attributes>
	</mapping>

	<!-- UNI level QoS -->
	<mapping>
		<attributes>
			<prefix>configure qos</prefix>
			<miniAttributes>2</miniAttributes>
			<attribute>
				<cliname>interface</cliname>
				<dbTable>QosUni</dbTable>
				<dbAttribute>logId</dbAttribute>
				<index>logId(regx|1/1/|(32,8,-2)(23,9,1)(16,7,1))</index>
				<parser>xref|1/1/|(32,8,-2)(23,9,1)(16,7,1)</parser>
			</attribute>
			<attribute>
				<cliname>scheduler-node</cliname>
				<dbTable>QosUni</dbTable>
				<dbAttribute>scnProf</dbAttribute>
				<index>logId(regx|1/1/|(32,8,-2)(23,9,1)(16,7,1))</index>
				<parser>ref|name:|(QosScNode:Index:Name)</parser>
			</attribute>
		</attributes>
	</mapping>
</mappings>

=== garfieldyao/dbexport/mapping/DataMapping3_ont.xml
<?xml version="1.0" encoding="UTF-8"?>
<mappings xmlns="http://www.garfield.com/MappingSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.garfield.com/MappingSchema MappingSchema.xsd ">
	<!-- configure equipment ont interface -->
	<mapping>
		<attributes>
			<prefix>configure equipment ont</prefix>
			<miniAttributes>1</miniAttributes>
			<attribute>
				<cliname>interface</cliname>
				<dbTable>ontConfig</dbTable>
				<dbAttribute>index</dbAttribute>
				<index>index(regx:1/1/:(16,8,-2)(7,9,1)(0,7,1))</index>
				<!--index>index1(regx:1/1/:(16,8,-2)(7,9,1)(0,7,1));index2(1)</index -->
				<parser>regx:1/1/:(16,8,-2)(7,9,1)(0,7,1)</parser>
			</attribute>
			<attribute>
				<cliname>sw-ver-pland</cliname>
				<dbTable>ontConfig</dbTable>
				<dbAttribute>planSw</dbAttribute>
				<index>index(regx:1/1/:(16,8,-2)(7,9,1)(0,7,1))</index>
			</attribute>
			<attribute>
				<cliname>battery-bkup</cliname>
				<dbTable>ontConfig</dbTable>
				<dbAttribute>batBkup</dbAttribute>
				<index>index(regx:1/1/:(16,8,-2)(7,9,1)(0,7,1))</index>
				<parser>enum:(0x0,disable)(0x1,enable)</parser>
				<default>disable</default>
			</attribute>
			<attribute>
				<cliname>berint</cliname>
				<dbTable>ontConfig</dbTable>
				<dbAttribute>berItv</dbAttribute>
				<index>index(regx:1/1/:(16,8,-2)(7,9,1)(0,7,1))</index>
				<default>8000</default>
			</attribute>
			<attribute>
				<cliname>desc1</cliname>
				<dbTable>ontConfig</dbTable>
				<dbAttribute>subDat1</dbAttribute>
				<index>index(regx:1/1/:(16,8,-2)(7,9,1)(0,7,1))</index>
			</attribute>
			<attribute>
				<cliname>desc2</cliname>
				<dbTable>ontConfig</dbTable>
				<dbAttribute>subDat2</dbAttribute>
				<index>index(regx:1/1/:(16,8,-2)(7,9,1)(0,7,1))</index>
			</attribute>
			<attribute>
				<cliname>provversion</cliname>
				<dbTable>ontConfig</dbTable>
				<dbAttribute>provVer</dbAttribute>
				<index>index(regx:1/1/:(16,8,-2)(7,9,1)(0,7,1))</index>
				<default>*</default>
			</attribute>
			<attribute>
				<cliname>sernum</cliname>
				<dbTable>ontConfig</dbTable>
				<dbAttribute>serNum</dbAttribute>
				<index>index(regx:1/1/:(16,8,-2)(7,9,1)(0,7,1))</index>
				<parser>class:com.mars.dbexport.service.parse.OntSnParser</parser>
				<default>ALCL:00000000</default>
			</attribute>
			<attribute>
				<cliname>subslocid</cliname>
				<dbTable>ontConfig</dbTable>
				<dbAttribute>slid</dbAttribute>
				<index>index(regx:1/1/:(16,8,-2)(7,9,1)(0,7,1))</index>
				<default>WILDCARD</default>
			</attribute>
			<attribute>
				<cliname>fec-up</cliname>
				<dbTable>ontConfig</dbTable>
				<dbAttribute>fecUp</dbAttribute>
				<index>index(regx:1/1/:(16,8,-2)(7,9,1)(0,7,1))</index>
				<parser>enum:(0x0,disable)(0x1,enable)</parser>
				<default>disable</default>
			</attribute>
			<attribute>
				<cliname>bridge-map-mode</cliname>
				<dbTable>ontConfig</dbTable>
				<dbAttribute>brMapMd</dbAttribute>
				<index>index(regx:1/1/:(16,8,-2)(7,9,1)(0,7,1))</index>
				<parser>enum:(0x5,1-mp-bridge-map-filter)(0x7,n-mp-bridge-map-filter)</parser>
				<default>1-mp-bridge-map-filter</default>
			</attribute>
			<attribute>
				<cliname>pwr-shed-prof-id</cliname>
				<dbTable>ontConfig</dbTable>
				<dbAttribute>pwrShed</dbAttribute>
				<index>index(regx:1/1/:(16,8,-2)(7,9,1)(0,7,1))</index>
				<parser>auto:(0x0,none)</parser>
				<default>none</default>
			</attribute>
			<attribute>
				<cliname>ont-enable</cliname>
				<dbTable>ontConfig</dbTable>
				<dbAttribute>OntEnDi</dbAttribute>
				<index>index(regx:1/1/:(16,8,-2)(7,9,1)(0,7,1))</index>
				<parser>enum:(0x0,auto)(0x1,disable)(0x2,enable)</parser>
				<default>auto</default>
			</attribute>
			<attribute>
				<cliname>p2p-enable</cliname>
				<dbTable>ontConfig</dbTable>
				<dbAttribute>eptpEn</dbAttribute>
				<index>index(regx:1/1/:(16,8,-2)(7,9,1)(0,7,1))</index>
				<parser>enum:(0x0,disable)(0x1,enable)</parser>
				<default>disable</default>
			</attribute>
			<attribute>
				<cliname>sw-dnload-version</cliname>
				<dbTable>ontConfig</dbTable>
				<dbAttribute>dldSw</dbAttribute>
				<index>index(regx:1/1/:(16,8,-2)(7,9,1)(0,7,1))</index>
				<default>DISABLED</default>
			</attribute>
			<attribute>
				<cliname>plnd-var</cliname>
				<dbTable>ontConfig</dbTable>
				<dbAttribute>plVar</dbAttribute>
				<index>index(regx:1/1/:(16,8,-2)(7,9,1)(0,7,1))</index>
				<default></default>
			</attribute>
			<attribute>
				<cliname>rf-filter</cliname>
				<dbTable>ontConfig</dbTable>
				<dbAttribute>ontVdRF</dbAttribute>
				<index>index(regx:1/1/:(16,8,-2)(7,9,1)(0,7,1))</index>
				<parser>enum:(0x0,pass-none)(0x1,pass-low)(0x2,pass-low-high)</parser>
				<default>pass-low-high</default>
			</attribute>
			<attribute>
				<cliname>us-police-mode</cliname>
				<dbTable>ontConfig</dbTable>
				<dbAttribute>usPolic</dbAttribute>
				<index>index(regx:1/1/:(16,8,-2)(7,9,1)(0,7,1))</index>
				<parser>enum:(0x0,local)(0x1,network)</parser>
				<default>local</default>
			</attribute>
			<attribute>
				<cliname>enable-aes</cliname>
				<dbTable>ontConfig</dbTable>
				<dbAttribute>aesEnbl</dbAttribute>
				<index>index(regx:1/1/:(16,8,-2)(7,9,1)(0,7,1))</index>
				<parser>enum:(0x0,disable)(0x1,enable)</parser>
				<default>disable</default>
			</attribute>
			<attribute>
				<cliname>voip-allowed</cliname>
				<dbTable>ontConfig</dbTable>
				<dbAttribute>voipCap</dbAttribute>
				<index>index(regx:1/1/:(16,8,-2)(7,9,1)(0,7,1))</index>
				<parser>enum:(0x0,disable)(0x1,enable)(0x2,iphost)(0x3,veip)</parser>
				<default>disable</default>
			</attribute>
			<attribute>
				<cliname>iphc-allowed</cliname>
				<dbTable>ontConfig</dbTable>
				<dbAttribute>iphcMd</dbAttribute>
				<index>index(regx:1/1/:(16,8,-2)(7,9,1)(0,7,1))</index>
				<parser>enum:(0x0,disable)(0x1,enable)</parser>
				<default>disable</default>
			</attribute>
			<attribute>
				<cliname>log-auth-id</cliname>
				<dbTable>ontConfig</dbTable>
				<dbAttribute>authID</dbAttribute>
				<index>index(regx:1/1/:(16,8,-2)(7,9,1)(0,7,1))</index>
				<default></default>
			</attribute>
			<attribute>
				<cliname>log-auth-pwd</cliname>
				<dbTable>ontConfig</dbTable>
				<dbAttribute>authPw</dbAttribute>
				<index>index(regx:1/1/:(16,8,-2)(7,9,1)(0,7,1))</index>
				<default></default>
			</attribute>
			<attribute>
				<cliname>cvlantrans-mode</cliname>
				<dbTable>ontConfig</dbTable>
				<dbAttribute>xcvmode</dbAttribute>
				<index>index(regx:1/1/:(16,8,-2)(7,9,1)(0,7,1))</index>
				<parser>enum:(0x0,remote)(0x1,local)</parser>
				<default>remote</default>
			</attribute>
		</attributes>
	</mapping>

	<mapping>
		<attributes>
			<prefix>configure equipment ont</prefix>
			<miniAttributes>2</miniAttributes>
			<attribute>
				<cliname>interface</cliname>
				<dbTable>ontConfig</dbTable>
				<dbAttribute>index</dbAttribute>
				<index>index(regx:1/1/:(16,8,-2)(7,9,1)(0,7,1))</index>
				<parser>regx:1/1/:(16,8,-2)(7,9,1)(0,7,1)</parser>
			</attribute>
			<attribute>
				<cliname>slid-visibility</cliname>
				<dbTable>ontConfig</dbTable>
				<dbAttribute>slidAvl</dbAttribute>
				<index>index(regx:1/1/:(16,8,-2)(7,9,1)(0,7,1))</index>
				<parser>enum:(0x0,disabled)(0x1,enabled-slid-on)(0x2,enabled-all)</parser>
				<default>disabled</default>
			</attribute>
			<attribute>
				<cliname>admin-state</cliname>
				<dbTable>ontConfig</dbTable>
				<dbAttribute>admin</dbAttribute>
				<index>index(regx:1/1/:(16,8,-2)(7,9,1)(0,7,1))</index>
				<parser>enum:(0x1,up)(0x2,down)</parser>
				<default>down</default>
			</attribute>
		</attributes>
	</mapping>

	<mapping>
		<attributes>
			<prefix>configure equipment ont</prefix>
			<miniAttributes>3</miniAttributes>
			<attribute>
				<cliname>interface</cliname>
				<dbTable>ontConfig</dbTable>
				<dbAttribute>index</dbAttribute>
				<index>index(regx:1/1/:(16,8,-2)(7,9,1)(0,7,1))</index>
				<parser>regx:1/1/:(16,8,-2)(7,9,1)(0,7,1)</parser>
			</attribute>
			<attribute>
				<cliname>ethernet</cliname>
				<dbTable>ontConfig</dbTable>
				<dbAttribute>null</dbAttribute>
				<index>index(regx:1/1/:(16,8,-2)(7,9,1)(0,7,1))</index>
				<parser>bool:</parser>
				<novalue>true</novalue>
			</attribute>
			<attribute>
				<cliname>ont-pm-collect</cliname>
				<dbTable>ontConfig</dbTable>
				<dbAttribute>ethPmEn</dbAttribute>
				<index>index(regx:1/1/:(16,8,-2)(7,9,1)(0,7,1))</index>
				<parser>enum:(0x1,enable)(0x2,disable)</parser>
				<default>disable</default>
			</attribute>
		</attributes>
	</mapping>
</mappings>

=== garfieldyao/dbexport/mapping/DataMapping55_vlanport.xml
<?xml version="1.0" encoding="UTF-8"?>
<mappings xmlns="http://www.garfield.com/MappingSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.garfield.com/MappingSchema MappingSchema.xsd ">
	<!-- configure vlan id -->
	<mapping>
		<attributes>
			<prefix>configure bridge</prefix>
			<miniAttributes>2</miniAttributes>
			<sortor>com.mars.dbexport.service.sortor.GenericSortor</sortor>
			<attribute>
				<cliname>port</cliname>
				<dbTable>portVlanTbl</dbTable>
				<dbAttribute>logic</dbAttribute>
				<index>slot;logic</index>
				<parser>route(portTbl?(slot,2,4:bsSlot,2,4)(logPort,2,4:bsLog,2,4))(multi(xref|1/1/|lanConfig|(bsSlot,2,4:index,2,4)(bsLog,2,4:itfmLog,2,4)|(index,16,8,-2)(raw:/)(index,7,9,1)(raw:/)(index,0,7,1)(raw:/)(slot,0,0,0)(raw:/)(port,0,0,0);xref|1/1/|voipUni|(bsSlot,2,4:index,2,4)(bsLog,2,4:itfmLog,2,4)|(index,16,8,-2)(raw:/)(index,7,9,1)(raw:/)(index,0,7,1)(raw:/)(raw:vuni)))</parser>
			</attribute>
			<attribute>
				<cliname>vlan-id</cliname>
				<dbTable>portVlanTbl</dbTable>
				<dbAttribute>uvid</dbAttribute>
				<index>slot;logic</index>
				<parser>class:com.mars.dbexport.service.parse.VlanIdParser</parser>
			</attribute>
			<attribute>
				<cliname>network-vlan</cliname>
				<dbTable>portVlanTbl</dbTable>
				<dbAttribute>uvid</dbAttribute>
				<index>slot;logic</index>
				<parser>select(istrans)?((0x0?route(attachtbl?(slot,2,4:slot,2,4)(logic,2,4:logic,2,4))(fwdId>>class:com.mars.dbexport.service.parse.VlanIdParser))(0x1?raw:stacked:0:4097))</parser>
				<default>stacked:0:4097</default>
			</attribute>
			<attribute>
				<cliname>vlan-scope</cliname>
				<dbTable>portVlanTbl</dbTable>
				<dbAttribute>istrans</dbAttribute>
				<index>slot;logic</index>
				<parser>enum:(0x0,local)(0x1,network)</parser>
				<default>network</default>
			</attribute>
			<attribute>
				<cliname>qos</cliname>
				<dbTable>portVlanTbl</dbTable>
				<dbAttribute>ply</dbAttribute>
				<index>slot;logic</index>
				<parser>select(ply)?((0x1?prior>>>regx|priority:|(0,0,0))(0x2?regid>>>ref|profile:|(regtbl:id:name)))</parser>
			</attribute>
			<attribute>
				<cliname>qos-profile</cliname>
				<dbTable>portVlanTbl</dbTable>
				<dbAttribute>qosid</dbAttribute>
				<index>slot;logic</index>
				<parser>ref|name:|(QosSessions:Index:Name)</parser>
			</attribute>
			<attribute>
				<cliname>prior-best-effort</cliname>
				<dbTable>portVlanTbl</dbTable>
				<dbAttribute>plist</dbAttribute>
				<index>slot;logic</index>
				<parser>bool:7</parser>
				<novalue>true</novalue>
			</attribute>
			<attribute>
				<cliname>prior-background</cliname>
				<dbTable>portVlanTbl</dbTable>
				<dbAttribute>plist</dbAttribute>
				<index>slot;logic</index>
				<parser>bool:6</parser>
				<novalue>true</novalue>
			</attribute>
			<attribute>
				<cliname>prior-spare</cliname>
				<dbTable>portVlanTbl</dbTable>
				<dbAttribute>plist</dbAttribute>
				<index>slot;logic</index>
				<parser>bool:5</parser>
				<novalue>true</novalue>
			</attribute>
			<attribute>
				<cliname>prior-exc-effort</cliname>
				<dbTable>portVlanTbl</dbTable>
				<dbAttribute>plist</dbAttribute>
				<index>slot;logic</index>
				<parser>bool:4</parser>
				<novalue>true</novalue>
			</attribute>
			<attribute>
				<cliname>prior-ctrl-load</cliname>
				<dbTable>portVlanTbl</dbTable>
				<dbAttribute>plist</dbAttribute>
				<index>slot;logic</index>
				<parser>bool:3</parser>
				<novalue>true</novalue>
			</attribute>
			<attribute>
				<cliname>prior-less-100ms</cliname>
				<dbTable>portVlanTbl</dbTable>
				<dbAttribute>plist</dbAttribute>
				<index>slot;logic</index>
				<parser>bool:2</parser>
				<novalue>true</novalue>
			</attribute>
			<attribute>
				<cliname>prior-less-10ms</cliname>
				<dbTable>portVlanTbl</dbTable>
				<dbAttribute>plist</dbAttribute>
				<index>slot;logic</index>
				<parser>bool:1</parser>
				<novalue>true</novalue>
			</attribute>
			<attribute>
				<cliname>prior-nw-ctrl</cliname>
				<dbTable>portVlanTbl</dbTable>
				<dbAttribute>plist</dbAttribute>
				<index>slot;logic</index>
				<parser>bool:0</parser>
				<novalue>true</novalue>
			</attribute>
			<attribute>
				<cliname>in-qos-prof-name</cliname>
				<dbTable>portVlanTbl</dbTable>
				<dbAttribute>tcProId</dbAttribute>
				<index>slot;logic</index>
				<parser>ref|name:|(QosInProf:Index:Name)</parser>
				<default>name:Default_TC0</default>
			</attribute>
			<attribute>
				<cliname>max-up-qos-policy</cliname>
				<dbTable>portVlanTbl</dbTable>
				<dbAttribute>polNbr</dbAttribute>
				<index>slot;logic</index>
				<default>0</default>
			</attribute>
			<attribute>
				<cliname>max-ip-antispoof</cliname>
				<dbTable>portVlanTbl</dbTable>
				<dbAttribute>staIp</dbAttribute>
				<index>slot;logic</index>
				<default>65535</default>
			</attribute>
			<attribute>
				<cliname>max-unicast-mac</cliname>
				<dbTable>portVlanTbl</dbTable>
				<dbAttribute>maxMac</dbAttribute>
				<index>slot;logic</index>
				<default>65535</default>
			</attribute>
		</attributes>
	</mapping>
</mappings>

=== garfieldyao/dbexport/mapping/DataMapping50_bridge.xml
<?xml version="1.0" encoding="UTF-8"?>
<mappings xmlns="http://www.garfield.com/MappingSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.garfield.com/MappingSchema MappingSchema.xsd ">
	<!-- configure vlan id -->
	<mapping>
		<attributes>
			<prefix>configure bridge</prefix>
			<miniAttributes>2</miniAttributes>
			<sortor>com.mars.dbexport.service.sortor.GenericSortor</sortor>
			<attribute>
				<cliname>port</cliname>
				<dbTable>portTbl</dbTable>
				<dbAttribute>bsLog</dbAttribute>
				<index>bsSlot;bsLog</index>
				<parser>multi(xref|1/1/|lanConfig|(bsSlot,2,4:index,2,4)(bsLog,2,4:itfmLog,2,4)|(index,16,8,-2)(raw:/)(index,7,9,1)(raw:/)(index,0,7,1)(raw:/)(slot,0,0,0)(raw:/)(port,0,0,0);xref|1/1/|voipUni|(bsSlot,2,4:index,2,4)(bsLog,2,4:itfmLog,2,4)|(index,16,8,-2)(raw:/)(index,7,9,1)(raw:/)(index,0,7,1)(raw:/)(raw:vuni))</parser>
			</attribute>
			<attribute>
				<cliname>pvid</cliname>
				<dbTable>portTbl</dbTable>
				<dbAttribute>pvid</dbAttribute>
				<index>bsSlot;bsLog</index>
				<parser>class:com.mars.dbexport.service.parse.VlanIdParser</parser>
			</attribute>
			<attribute>
				<cliname>default-priority</cliname>
				<dbTable>portTbl</dbTable>
				<dbAttribute>portPr</dbAttribute>
				<index>bsSlot;bsLog</index>
				<default>0</default>
			</attribute>
			<attribute>
				<cliname>mac-learn-off</cliname>
				<dbTable>portTbl</dbTable>
				<dbAttribute>lnStat</dbAttribute>
				<index>bsSlot;bsLog</index>
				<parser>bool:-0</parser>
				<novalue>true</novalue>
			</attribute>
			<attribute>
				<cliname>max-unicast-mac</cliname>
				<dbTable>portTbl</dbTable>
				<dbAttribute>maxAdd</dbAttribute>
				<index>bsSlot;bsLog</index>
				<default>1</default>
			</attribute>
			<attribute>
				<cliname>qos-profile</cliname>
				<dbTable>portTbl</dbTable>
				<dbAttribute>qosProf</dbAttribute>
				<index>bsSlot;bsLog</index>
				<parser>ref|name:|(QosSessions:Index:Name)</parser>
			</attribute>
			<attribute>
				<cliname>prio-regen-prof</cliname>
				<dbTable>portTbl</dbTable>
				<dbAttribute>priReg</dbAttribute>
				<index>bsSlot;bsLog</index>
				<parser>ref|(regtbl:id:name)</parser>
			</attribute>
			<attribute>
				<cliname>max-committed-mac</cliname>
				<dbTable>portTbl</dbTable>
				<dbAttribute>cmtMax</dbAttribute>
				<index>bsSlot;bsLog</index>
				<default>65535</default>
			</attribute>
			<attribute>
				<cliname>mirror-mode</cliname>
				<dbTable>portTbl</dbTable>
				<dbAttribute>mirMode</dbAttribute>
				<index>bsSlot;bsLog</index>
				<parser>enum:(0x0,disable)(0x3,overwrite-outer-vlan)</parser>
				<default>disable</default>
			</attribute>
			<attribute>
				<cliname>mirror-vlan</cliname>
				<dbTable>portTbl</dbTable>
				<dbAttribute>mirVlan</dbAttribute>
				<index>bsSlot;bsLog</index>
				<default>0</default>
			</attribute>
			<attribute>
				<cliname>pvid-tagging-flag</cliname>
				<dbTable>portTbl</dbTable>
				<dbAttribute>pvidTag</dbAttribute>
				<index>bsSlot;bsLog</index>
				<parser>enum:(0x0,onu)(0x1,olt)</parser>
				<default>onu</default>
			</attribute>
		</attributes>
	</mapping>
</mappings>
